version: "3"
services:
    # Node service
    serverless-node-culqi:
        build: .
        container_name: serverless-node-culqi
        working_dir: /app
        ports:
            - "3001:3000"
        volumes:
            - ./:/app
        networks:
            - serverless-network-culqi
        depends_on:
            - serverless-postgres-culqi
            - serverless-redis-culqi

    serverless-vue-culqi:
        build:
            context: .
            dockerfile: vue.Dockerfile
        container_name: serverless-vue-culqi
        working_dir: /app
        ports:
            - "8081:8080"
        volumes:
            - ./microfrontend/:/app
        networks:
            - serverless-network-culqi
        depends_on:
            - serverless-node-culqi

    # Postgres database service
    serverless-postgres-culqi:
        image: postgres:15
        container_name: serverless-postgres-culqi
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=culqi_db
        networks:
            - serverless-network-culqi

    serverless-postgres-culqi-test:
        image: postgres:15
        container_name: serverless-postgres-culqi-test
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=postgres_test
            - POSTGRES_PASSWORD=postgres_test
            - POSTGRES_DB=culqi_db_test
        networks:
            - serverless-network-culqi

    serverless-redis-culqi: # Name of container
        image: redis
        container_name: serverless-redis-culqi
        ports:
            - 6380:6379
        volumes:
            - redis:/data
        networks:
            - serverless-network-culqi

volumes:
    redis:
        driver: local

networks:
    serverless-network-culqi:
        driver: bridge