service: serverless-http-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: dist/handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline