service: serverless-http-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 192
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  endpointType: REGIONAL
  apiName: CULQI CHALLENGE API

custom:
  serverless-offline:
    host: 0.0.0.0
    printOutput: true
    cacheInvalidationRegex: 'node_modules/'

functions:
  hello:
    handler: dist/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  token-create:
    handler: dist/src/handlers/token/create.handler
    events:
      - httpApi:
          path: /token
          method: post
  token-get:
    handler: dist/src/handlers/token/get.handler
    events:
      - httpApi:
          path: /token
          method: get

plugins:
  - serverless-offline